### PR TITLE
Added entries for ISO 639-1/2

### PR DESCRIPTION
**Pull request by andrea-perego**

### CODE REVIEW

**Comment by andrea-perego** [comment]
@tobie , @dr-shorthair , it seems that the [validation error](https://travis-ci.org/tobie/specref/builds/364183619?utm_source=github_status&utm_medium=notification) is caused by the regex used for field `isoNumber`, wich expects a 4-digit number (whereas "ISO 639-*" has a 3-digit one):

````
 * String does not match pattern: ^ISO(\/IEC)?(\/((TS)|(DIS)|(FDIS)))? \d{4,}(\-\d+)?(\:\d{4})?$
    "ISO 639-1:2002"
````

**Comment by tobie** [comment]
You want to fix that pattern in the schemas accordingly.

**Comment by dr-shorthair** [comment]
4 digits is clearly incorrect expectation

**Comment by andrea-perego** [comment]
@tobie , @dr-shorthair , thanks for your feedback.

I've just created the relevant PR: #455

**Comment by tobie** [comment]
You'll have to rebase, imho.

**Comment by andrea-perego** [comment]
Thanks, @tobie . I'll do that.

**Comment by andrea-perego** [comment]
I think can try to add the whole ISO 639 series. I'll close this one and create another PR.

**Pull request closed without merging**
