### PR TITLE
Expose versions.

### PR DESCRIPTION
**Pull request by tobie**
This exposes the version ID of specs when present. So for example, instead of exposing the following for HTML5:

```json
{
    "html5": {
        "authors": [
            "Ian Hickson",
            "Robin Berjon",
            "Steve Faulkner",
            "Travis Leithead",
            "Erika Doyle Navara",
            "Edward O'Connor",
            "Silvia Pfeiffer"
        ],
        "date": "28 October 2014",
        "deliveredBy": [
            {
                "shortname": "html",
                "url": "http://www.w3.org/html/wg/"
            }
        ],
        "edDraft": "http://www.w3.org/html/wg/drafts/html/master/",
        "href": "http://www.w3.org/TR/html5/",
        "id": "html5",
        "publisher": "W3C",
        "status": "REC",
        "title": "HTML5"
    }
}
```

This is exposed instead:

```JSON
{
    "html5": {
        "authors": [
            "Ian Hickson",
            "Robin Berjon",
            "Steve Faulkner",
            "Travis Leithead",
            "Erika Doyle Navara",
            "Edward O'Connor",
            "Silvia Pfeiffer"
        ],
        "date": "28 October 2014",
        "deliveredBy": [
            {
                "shortname": "html",
                "url": "http://www.w3.org/html/wg/"
            }
        ],
        "edDraft": "http://www.w3.org/html/wg/drafts/html/master/",
        "href": "http://www.w3.org/TR/html5/",
        "id": "html5",
        "publisher": "W3C",
        "status": "REC",
        "title": "HTML5",
        "versions": [
            "html5-20080122",
            "html5-20080610",
            "html5-20090212",
            "html5-20090423",
            "html5-20090825",
            "html5-20100304",
            "html5-20100624",
            "html5-20101019",
            "html5-20110113",
            "html5-20110405",
            "html5-20110525",
            "html5-20120329",
            "html5-20121025",
            "html5-20121217",
            "html5-20130806",
            "html5-20140204",
            "html5-20140429",
            "html5-20140617",
            "html5-20140731",
            "html5-20140916",
            "html5-20141028"
        ]
    }
}
```

### CODE REVIEW

**Comment by darobin** [comment]
LGTM. @dontcallmedom we could use this information in spec-generator in order to set the previous version, it would be a *lot* simpler than the current rigmarole.

**Comment by dontcallmedom** [comment]
@darobin all the more so that the spec-generator code to read tr.rdf is a shameless derivation of specref's code :)

**Comment by marcoscaceres** [comment]
LGTM.

**Comment by tobie** [comment]
An opinion on the sort order?

Also, watch out for some of the specs which have non-date-based keys, eg `xml-4e`:

```JSON
{
    "xml": {
        "authors": [
            "Tim Bray",
            "Jean Paoli",
            "Michael Sperberg-McQueen",
            "Eve Maler",
            "Fran\u00e7ois Yergeau"
        ],
        "date": "26 November 2008",
        "deliveredBy": [
            {
                "shortname": "xml_core",
                "url": "http://www.w3.org/XML/Core/"
            }
        ],
        "etAl": true,
        "href": "http://www.w3.org/TR/xml",
        "id": "xml",
        "publisher": "W3C",
        "status": "REC",
        "title": "Extensible Markup Language (XML) 1.0 (Fifth Edition)",
        "versions": [
            "xml-4e",
            "xml-20081126",
            "xml-20080205",
            "xml-20060816",
            "xml-20060614",
            "xml-20040204",
            "xml-20031030",
            "xml-20001006",
            "xml-20000814",
            "xml-19980210",
            "xml-19971208",
            "xml-19961114"
        ]
    }
}
```

**Comment by tobie** [comment]
Deployed.

**Pull request merged**
