### PR TITLE
Update WG21 references, include WG21 in auto-update scripts

### LINKED ISSUE #469: WG21 missing entries
WG21 seems to be missing entries, for example:

screen shot 2018-06-20 at 2 19 25 pm

Looking at wg21.link/index.json there are r0 through r6 versions of this paper, but specref doesn't know about all of them.

/cc @m-ou-se @jyasskin

### PR DESCRIPTION
**Pull request by tobie**
Closes #469.

### CODE REVIEW

**Comment by jfbastien** [comment]
Confirmed that it now works (and bikeshed is happy again). Thank!

**Comment by tobie** [comment]
Is your version of Bikeshed up to date?

**Comment by jfbastien** [comment]
Yeah I ran `bikeshed update` just before filing the issue. After your fix I did `bikeshed update` again and it found the paper I was trying to refer to.

**Comment by tobie** [comment]
That updates the data, not the code, for which you have to use git.

**Comment by jfbastien** [comment]
Right but the data was what I needed, no? Unless bikeshed started using specref differently?

**Comment by tobie** [comment]
Yeah. It pulls WG21 directly.

**Comment by m-ou-se** [comment]
Note that wg21.link also publishes its index in specref format: https://wg21.link/specref.json
Might be useful.

**Pull request merged**
