### PR TITLE
Adding second author to image-capture spec

### PR DESCRIPTION
**Pull request by miguelao**

### CODE REVIEW

**Comment by tobie** [comment]
That should be automatic the next time the spec gets published on /TR. 

Whatever you fix here would get overwritten nearly immediately by the sync bot.

**Comment by miguelao** [comment]
That'd work for me, but I have been co-editor since ~June and the authors list hasn't updated...

**Comment by tobie** [comment]
Have you submitted a new WD or are you planning to soon?

**Comment by miguelao** [comment]
IIUC we're working now against `gh-pages` branch and do no timed releases, @dontcallmedom keep me true please.

**Comment by tobie** [comment]
Sounds like an upstream issue. Cc'ed you in the email I just sent.

**Pull request closed without merging**
