### PR TITLE
Add CSS aliases

### PR DESCRIPTION
**Pull request by arronei**
* additional aliases based on the great CSS rename

### CODE REVIEW

**Comment by tobie** [comment]
Mmm. How come those aren't in there automatically. :-/

**Comment by tobie** [comment]
Mmm, I guess none of those reached WD with their new names yet.

Slightly concerned about what's going to happen once these are merged automatically, though. Will this break stuff? I have no idea.

**Comment by tabatkins** [comment]
Because the webmaster screwed up the publishing requests. :/  Note, for example, that `/TR/css-animations/` works, but not `/TR/css-animations-1/`.

**Comment by tobie** [comment]
Should we attempt an upstream fix, then?

**Comment by tabatkins** [comment]
Yeah, that's the right thing to do.

**Comment by arronei** [comment]
@tobie @tabatkins should we close this PR then?

**Comment by tobie** [comment]
Yeah, if the CSS WG plans to get those fixed on W3C's end, so that <https://www.w3.org/TR/css-color-3/> effectively redirect to <https://www.w3.org/TR/css3-color/>, Specref will get the aliasing for free the next time it parses the RDF files. We also won't incur a maintenance cost that way.

**Pull request closed without merging**
