### PR TITLE
Fixed DCAT-AP and GeoDCAT-AP entries

### PR DESCRIPTION
**Pull request by andrea-perego**
- Fixed version date in DCAT-AP
- Replaced original URLs with the corresponding permanent URIs

### CODE REVIEW

**Comment by tobie** [comment]
What happened there?

**Comment by andrea-perego** [comment]
I was trying to fix the date used as version key (which I'm quite sure it is not used anywhere), by replacing it with the correct date, but this change didn't pass the validation.

**Comment by tobie** [comment]
Oh, gotcha!

What you want to do in such cases is to add an alias of the incorrect key to the fixed one. Like that you're sure you don't break anything.

**Comment by andrea-perego** [comment]
Thanks, @tobie . I guessed that too late. 

BTW, can aliases be specified at the version level? I mean, like this

````json
"spec": {
  ...
  "versions":{
    "20101010":{
      "aliasOf":"20202020"
    },
    "20202020":{
      ...
    },
  }
}
````

or they should rather be at the top level?

````json
"spec-20101010":{
  "aliasOf":"20202020"
},

"spec": {
  ...
  "versions":{
    "20202020":{
      ...
    },
  }
}
````

**Comment by tobie** [comment]
I think both work.

**Comment by andrea-perego** [comment]
I'll give it a try, then.

**Pull request closed without merging**
