### PR TITLE
Fix test after alias changes for hr-time and resource-timing

### PR DESCRIPTION
**Pull request by deniak**

### CODE REVIEW

**Review by tobie — CHANGES_REQUESTED** [review]
Thanks for doings this.

What we need to do instead here is manually alias those so we don’t remove references that folks could be relying on.

**Comment by deniak** [comment]
> What we need to do instead here is manually alias those so we don’t remove references that folks could be relying on.

The problem is that these references break the duplicate tests as far I understand how this works.

**Comment by deniak** [comment]
oh, I think I understand what you mean now. Let me give it a try

**Comment by deniak** [comment]
@tobie, I jsut added the aliases

**Review by tobie — APPROVED** [review]

**Pull request merged**
