### PR TITLE
Add aliases for all the 'correct' CSS spec names known by Shepherd, b…

### PR DESCRIPTION
**Pull request by tabatkins**
…ut not yet known in the W3C systems.

### CODE REVIEW

**Comment by tobie** [comment]
If these aliases are going to end up in W3C data, it might be more future-proof to put them all in w3c.json instead of biblio.json.

**Comment by tabatkins** [comment]
Isn't that auto-generated?

**Comment by tabatkins** [comment]
(There's already several of these CSS aliases in biblio.json anyway.)

**Comment by tobie** [comment]
It _is_, but it keeps existing data unless it gets overwritten.

**Comment by tobie** [comment]
Yeah, I know we're not super consistent here. My concern is essentially that there might be conflicts once those get added to W3C data. This won't hapen if the data's in w3c.json. It _might_ if it's in biblio.json.

**Comment by tobie** [comment]
Not a deal blocker anyway. Feel free to merge as is.

**Comment by tabatkins** [comment]
Ah, kk. Will those conflicts end up showing up in your analytics or something, so we can remove them?

**Comment by tabatkins** [comment]
(I can move all the CSS-related ones over to w3c.json in another PR if you think that's better.)

**Comment by tobie** [comment]
If it's _really_ an issue (Specref is 90% duck tape, so I'm never _sure_ whether something will break and thus err on the conservative side), we'll find out once W3C starts adding those in its tr.rdf file; the updating process will fatal and we'll just fix it then.

**Comment by tabatkins** [comment]
Works for me. ^_^

**Pull request merged**
