### PR TITLE
Update HIGHRES-TIME

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by tobie** [comment]
You probably just want to do:

```json
{
    "HIGHRES-TIME": {
        "aliasOf": "hr-time-2"
    }
}
```

**Comment by domenic** [comment]
hr-time-2 doesn't exist in biblio.json...

**Comment by tobie** [comment]
Yeah, but it does in w3c.json. I know this aliasing system across files is counterintuitive. Apologies. I hadn't thought things through fully when splitting the files up.

**Comment by domenic** [comment]
Got it. Pushed as an alias.

**Pull request merged**
