### PR TITLE
Added geospatial standards and other specifications from the OGC

### PR DESCRIPTION
**Pull request by ghobona**
This Pull Request adds the complete catalogue of specifications of the Open Geospatial Consortium (OGC). The catalogue includes OGC standards, extensions, profiles, best practices, engineering reports, discussion papers, and other specifications.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
"ogcNumber" is not a thing in our schema... I think you should just use `id` instead.

**Comment by andrea-perego** [comment]
@ghobona , please note that some of the OGC standards you included are already in SpecRef - see:

https://www.specref.org/?q=ogc

/cc @dr-shorthair

**Comment by marcoscaceres** [comment]
Oh, would be great to remove redundant ones. 

@tobie can probably provide guidance on what the best approach is.

**Comment by andrea-perego** [comment]
Actually, there was some discussion in the framework of the joint W3C/OGC Spatial Data on the Web WG/IG about the possibility of having OGC standards automatically harvested by SpecRef, as done for W3C ones. Not sure about the status of this.

@dr-shorthair , @rob-metalinkage , maybe you know.

**Comment by ghobona** [comment]
@marcoscaceres

Ok, I'll remove redundant ones and change "ogcNumber" to "id".

**Comment by tobie** [comment]
Hi, was your plan to resubmit this? I'd hate for all the work you did to be thrown away.

**Comment by ghobona** [comment]
@tobie
I'll resubmit in a few weeks time.

**Pull request closed without merging**
