### PR TITLE
Add microformats2 specifications

### PR DESCRIPTION
**Pull request by strugee**
/cc @tantek to make sure this is all right.

### CODE REVIEW

**Comment by tantek** [comment]
Better to use "status": "Living Specification" for all of them from an external perspective. Internally see http://microformats.org/wiki/process#Moving_from_Stage_to_Stage for draft vs spec vs standard if you're curious about the different levels according to microformats process. All of those are "living specs" as it were.

**Comment by tobie** [comment]
This LGTM.

Feel free to merge once you've addressed the changes requested by @tantek.

**Comment by strugee** [comment]
Pushed c14dfab05a2722fe4a17688a401c207c59861906 to address the status issue. Thanks for the write access :thumbsup: :tada:

**Comment by tobie** [comment]
@tantek, fwiw, the WHATWG folks tend to use the term "Living standard." I don't care either way.

**Comment by strugee** [comment]
@tobie based on http://microformats.org/wiki/process#Standard I guess the microformats folks differentiate between "specification" and "standard"

**Comment by tobie** [comment]
@strugee please don't _ever_ merge with checks pending.

Please also squash merges unless there's a god reason not to (e.g. preserve history).

**Comment by strugee** [comment]
@tobie ah sorry, I read that guideline in the README but figured it was so trivial there was no need to wait for Travis. I'll be more careful in the future. Should I force-push a squash for this merge?

**Comment by tobie** [comment]
> I read that guideline in the README but figured it was so trivial there was no need to wait for Travis.

A typo in the JSON and the deploy script just stalls until I go manually fix the problem.

>  Should I force-push a squash for this merge?

No, please don't.

**Comment by tobie** [comment]
Don't worry about it, though. :)

**Comment by tantek** [comment]
@tobie had not noticed that difference before, and the mf2 specs are consistently using "living specification" currently so let's stick with that for now. I'm open to switching to "living standard", no strong feelings there. Happy to make it an open question in the microformats community and have folks discuss it to see if there is a consensus either way.

**Pull request merged**
