### PR TITLE
Add ISO7812-1

### PR DESCRIPTION
**Pull request by marcoscaceres**
Used by payments wg

### CODE REVIEW

**Comment by marcoscaceres** [comment]
we should eventually make a "iso.json" file.... biblio.json is becoming quite the chunky monkey.

**Comment by marcoscaceres** [comment]
Didn't know that was a thing! Thanks.

**Comment by dr-shorthair** [comment]
Yes - that is the plan. I added "isoNumber" last week to the schema in anticipation. And then we would need scripts/iso.js to handle it  - but that is beyond my skillset I'm afraid.

**Comment by marcoscaceres** [comment]
> scripts/iso.js to handle it - but that is beyond my skillset I'm afraid.

What would it do? Maybe I can help?

**Comment by tobie** [comment]
> Didn't know that was a thing! Thanks.

It's not reflected in the API for now, FYI. Would this be something you'd want to expose in ReSpec?

**Comment by marcoscaceres** [comment]
Depends... I don't yet understand the value of it over "status". What would be the benefit to readers over what they get today? This is really a question for @dr-shorthair

**Comment by marcoscaceres** [comment]
Btw, can we merge this and then do all the ISO specs at once? I'm keen to get the spec that needs this out the door. Then I can also go back to focusing on improving ReSpec.

**Comment by tobie** [comment]
Sure, just please fix the status and we're good.

**Comment by marcoscaceres** [comment]
So, as ReSpec doesn't support `isoNumber` yet, I added both status and isoNumber... otherwise, there would be a gap when displaying the reference (because it would lack a status).

**Comment by tobie** [comment]
Feel free to merge once green

**Pull request merged**
