### PR TITLE
Update WICG refs with isolated contexts

### PR DESCRIPTION
**Pull request by shangl**

### CODE REVIEW

**Comment by shangl** [comment]
@tobie , friendly ping :). PTAL.

**Comment by tobie** [comment]
Why not upstream?

**Comment by tobie** [comment]
i.e. here: https://github.com/WICG/admin/blob/gh-pages/biblio.json

**Comment by GrapeGreen** [comment]
It's actually already there (see `ISOLATED-CONTEXTS`). We thought that adding this to the specref database could also make sense :)

The automatic update script for pulling refs from wicg into here seems to be broken.

**Comment by tobie** [comment]
Fixed in https://github.com/tobie/specref/commit/6e0f94c13b8cd525bd74c5675ab8f2af4c910231

**Pull request closed without merging**
