### PR TITLE
add ref for mathml-core

### PR DESCRIPTION
**Pull request by bkardell**

### CODE REVIEW

**Review by tobie — APPROVED** [review]
This LGTM. Not sure what the correct abbreviation is for CG drafts in the new process doc, though.

**Comment by bkardell** [comment]
Is this in reference to the short name or a specific property in here?

**Comment by tobie** [comment]
True status.

**Comment by bkardell** [comment]
The process links to several CGs, among those reporting requirements/respec suggest CG-Draft might be appropriate

**Comment by tobie** [comment]
Yeah, I guess we can always fix it later if need be.

**Pull request merged**
