### PR TITLE
Add MEDIAQUERIES and update MEDIAQ

### PR DESCRIPTION
**Pull request by annevk**
I don't quite understand why this didn't exist or why this is all versioned still, but so be it I guess. We better update these whenever -5 comes out.

### CODE REVIEW

**Comment by tobie** [comment]
Leveled specs are a mess.

**Comment by annevk** [comment]
I guess I can't touch MEDIAQ?

**Comment by annevk** [comment]
I just noticed I made a typo. I wrote MEDIAQEURIES instead of MEDIAQUERIES. Sigh.

**Comment by tobie** [comment]
:D you can either fix it yourself (you'll have to remove it from the json file that lists all of the spec short names so the tests pass), or I'll do it once I've dropped the kids to school.

**Comment by annevk** [comment]
#424.

**Pull request merged**
