### PR TITLE
Move REPORTING spec from WICG to W3C.

### PR DESCRIPTION
**Pull request by clelland**
Fixes: #574

### CODE REVIEW

**Comment by clelland** [comment]
I'm not 100% sure whether modifying wicg.json is okay here, but the spec is no longer returned from https://wicg.github.io/admin/biblio.json, so it should probably be removed.

**Comment by marcoscaceres** [comment]
I'll remove it from the upstream version too... this file is pulled from the WICG admin repo.

**Comment by marcoscaceres** [comment]
I misread the above... REPORTING is indeed gone from the upstream, so this should be correct.

**Comment by marcoscaceres** [comment]
Having said that, this should show up automatically once published at as a FPWD on W3C's TR.

**Comment by clelland** [comment]
Do you mean that REPORTING will move to w3c.json automatically? (And point to the ED?)

**Comment by ExE-Boss** [comment]
`reporting` already&nbsp;exists in&nbsp;`w3c.json` as&nbsp;`reporting‑1`, so&nbsp;this&nbsp;needs to&nbsp;be&nbsp;converted into&nbsp;an&nbsp;alias, which&nbsp;is&nbsp;what I’m&nbsp;doing in&nbsp;<https://github.com/tobie/specref/pull/578>.

**Pull request closed without merging**
