### PR TITLE
Adding entries of INSPIRE and ISA specifications

### PR DESCRIPTION
**Pull request by andrea-perego**
The proposed entries concern two sets of specifications, developed in the framework of EU activities, and implemented across Europe:
* [INSPIRE](http://inspire.ec.europa.eu/) (Infrastructure for spatial information in Europe)
* [EU ISA Programme](https://ec.europa.eu/isa) (Interoperability solutions for public administrations, businesses and citizens)

### CODE REVIEW

**Comment by tobie** [comment]
Thanks for your contributions.

The tests are failing because of the `deliveredBy` property, which was sort of hacked together a while back for a particular use case and really isn't designed to handle non-W3C specs.

I'm pushing a short fix for it, so we can merge this, but this is an issue that needs a longer term more robust solution.

How are you planning to use it?

**Comment by andrea-perego** [comment]
Thanks, @tobie . No urgent plans to use `deliveredBy`, but it would be nice to have. 

BTW, the INSPIRE & ISA specs are also referred to from some W3C TRs (in particular, from the Spatial Data on the Web and the Dataset Exchange WGs). Is `deliveredBy` required, in this case?

Thanks a lot for your help & support

**Comment by tobie** [comment]
> Is deliveredBy required, in this case?

No, it's something we use exclusively for a bot that tags web-platform-tests pull requests.

**Comment by tobie** [comment]
Anyway, thanks for your contribution!

A new version of Specref updated with these changes should auto-deploy within minutes. You can search  [www.specref.org](http://www.specref.org/) to check for it.

Don't hesitate to comment back here if you can't find your changes within 10 minutes; it's a sign something is off and I'll immediately look into it. Thanks!

Specref loosely follows the process described in [The Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html). You've thus been [granted commit access](https://github.com/tobie/specref/invitations) to the repo.

Please read-up on how to make [manual changes](https://github.com/tobie/specref#manual-changes), get non-trivial changes reviewed by someone (I'm sure you'll be a good judge of when that's necessary) and feel free to ask if something's unclear.

Thanks again!

**Comment by andrea-perego** [comment]
Thanks a lot, @tobie 

I would also like to anticipate that I plan to proposed additional entries in the days/next weeks concerning specifications used across some TRs of the W3C I mentioned earlier.

**Pull request merged**
