### PR TITLE
feat(biblio): add WebIDL-LS

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Because we can't have enough links to WebIDL 👍

**Comment by marcoscaceres** [comment]
Went with "WebIDL-LS" instead of L2. Also set status to "ED".

**Comment by tobie** [comment]
Frankly, I'm torn, here.

On one hand, I think WebIDL href should just point to the ED.
On the other I see @marcoscaceres's point, in which case I think WebIDL-2 should be an alias of WebIDL-LS.

**Comment by marcoscaceres** [comment]
Problem is that WebIDL-2 is already pointing to the wrong place (aliasOf: webIDL). Maybe no one is using that though and we can just take it over. I'm ok with correcting WebIDL-2 to point to the ED. Let's just do it.

**Comment by tobie** [comment]
OK, fixed.

Waiting for Travis, then deploying.

**Comment by marcoscaceres** [comment]
Awesome, thanks for fixing.

**Pull request merged**
