### PR TITLE
Move feature policy to W3C

### LINKED ISSUE #533: Move Feature Policy from WICG to W3C
It is on /TR now: https://www.w3.org/TR/feature-policy-1/

### PR DESCRIPTION
**Pull request by tobie**
Closes #533.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Note that I updated the WICG file downstream... #532 ?

**Comment by tobie** [comment]
So… the problem here is a bit more complex. There are safeguards to keep the data consistent against upstream changes. The problem is, until the spec surfaces in /TR (i.e. until the first public WD), allowing it to be removed from the WICG refs file would break a bunch of specs referencing it.

**Comment by marcoscaceres** [comment]
Agree and understood. I only made the change once it was on TR:
https://www.w3.org/TR/feature-policy/

**Comment by tobie** [comment]
Yes... except for some unknown reasons, the /TR RDF API exposes the new FEATURE-POLICY-1 URL, but not the FEATURE-POLICY -> FEATURE-POLICY-1 redirect (it usually does).

**Comment by marcoscaceres** [comment]
I'm just going to go and smash my head against the wall on your behalf for a while.

**Comment by tobie** [comment]
Give it a good 90 minutes.

**Pull request merged**
