### PR TITLE
DCAT alias

### PR DESCRIPTION
**Pull request by dr-shorthair**
Alias
DCAT --> vocab-dcat-3

### CODE REVIEW

**Comment by dr-shorthair** [comment]
@tidoust this one should be safe

**Comment by tidoust** [comment]
Tests do pass but note that's the same issue as in #834 that just gets postponed to a future date.

The `vocab-dcat-3` spec creates entries such as `vocab-dcat-3-20201217`. If `DCAT` is made an alias to `vocab-dcat-3`, then that means entries such as `DCAT-20201217` get created. If, later on, a level 4 gets worked on and you want to update `DCAT` to target `vocab-dcat-4` instead of `vocab-dcat-3`, that won't work because `DCAT-20201217` would then no longer exist. Again ,the right fix would be to have support for specification series (raised in #811) and the general guideline is "use references with levels" in the meantime.

I'm not trying to block this. Other entries got created using that model before, including some I fear I contributed. But that does not fit nicely with the way Specref models things for now.

**Comment by dr-shorthair** [comment]
So are you saying that there is currently no way to refer to version-free DCAT using specref. 
And no way to fix that. 

I'm editing the new edition of the W3C SSN Ontology and we wish to draw attention to the parallel between ObservationCollection and dcat:Dataset. That DCAT class is in all editions of DCAT, so the reference should reflect that. 

[vocab-dcat] links to a version that is clearly marked 'obsolete' so I don't want to use that. 
I guess I'll have to add a local entry in the config.js instead. That seems unsatisfactory.

**Comment by tidoust** [comment]
> So are you saying that there is currently no way to refer to version-free DCAT using specref.

That's correct. For example, there's no way to reference `css-color`. You have to choose between `css-color-3`, `css-color-4`, `css-color-5`, or `css-color-6`: https://www.specref.org/?q=css-color

> And no way to fix that.

No *good* way. There's always a way to force entries into Specref. If `DCAT` is made an alias of `vocab-dcat-3` then, when time comes to update the link to `vocab-dcat-4`, it is possible to force the creation of previous version entries in Specref, meaning to define entries such as:

```json
"DCAT-20201217": {
  "aliasOf": "vocab-dcat-3-20201217"
}
```

This will have to be done for all dated versions of `vocab-dcat-3`. That's the current workaround and there are entries done like this in the `w3c.json` file.

> I guess I'll have to add a local entry in the config.js instead. That seems unsatisfactory.

That seems like a good solution to solve your immediate problem. I suspect I'll look into adding support for specification series to Specref in a not too distant future because I need it as well. But that depends on other pending updates.

**Pull request closed without merging**
