### PR TITLE
Update ES262 and ES402

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by domenic** [comment]
Would you like to maintain an alias from ECMAS-402 to ECMA-402? It seems like a clear typo.

**Comment by tobie** [comment]
Mmm. I don't have an effective means of checking whether someone still relies on it. So yeah, I'd rather we left it around, as an alias, preferably.

**Comment by domenic** [comment]
OK cool, pushed with an alias.

**Comment by tobie** [comment]
Thanks!

**Pull request merged**
