### PR TITLE
Expose isbn and pages props.

### PR DESCRIPTION
**Pull request by tobie**
/cc @arronei

### CODE REVIEW

**Comment by tobie** [comment]
Curious as to whether there's interest from API consumers to use that info for book references. /cc @tabatkins, @marcoscaceres, @halindrome

**Comment by marcoscaceres** [comment]
I've personally never found myself needing to cite a book or journal in a spec. But it could be useful.

**Comment by tabatkins** [comment]
I'm happy to output as specific/useful a biblio reference as possible, so if there's more information about ISBN and pages, I can def use that.

**Comment by tobie** [comment]
http://www.specref.org/?q=0-13-000027-2

**Comment by marcoscaceres** [comment]
@tabatkins, let me know where you putting page numbers and ISBN (I.e., what bibliographical style you are using) and I'll do the same on ReSpec side.

**Pull request merged**
