### PR TITLE
Add a trailing slash to Selectors ED link

### PR DESCRIPTION
**Pull request by foolip**
Matches https://github.com/w3c/csswg-drafts/pull/2277.

### CODE REVIEW

**Comment by foolip** [comment]
Is it a bug that this wasn't auto-updated from the spec?

**Comment by tobie** [comment]
No. It would eventually. The next time the WG releases a working draft.

**Comment by foolip** [comment]
This was reverted by https://github.com/tobie/specref/commit/07fdd00b6b50fdd63bc17681859b3e7c7b68aba6. Where is specref still getting the no-slash URL from?

**Comment by tobie** [comment]
W3C’s API doesn’t reflect change in a spec until that spec is again published as a WD (not just as an ED).

**Comment by foolip** [comment]
Ugh, annoying.

**Comment by tobie** [comment]
🤷‍♂️

**Pull request merged**
