### PR TITLE
Moar HTTPS and use /multipage/ for HTML

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by tobie** [comment]
Happy to merge this but heads-up that some of these will be overwritten by the auto-update scripts.

**Comment by tobie** [comment]
@annevk, here's what the auto-update script does: 97a437d, the simplest way to fix this is in the script itself, imho, by adding them one by one to the [ED_DRAFTS dictionary](https://github.com/tobie/specref/blob/master/scripts/rdf.js#L41-L43).

**Comment by domenic** [comment]
Can we make the script just auto-rewrite all github.io URLs to https?

**Comment by tobie** [comment]
Yup, PR on its way.

**Comment by tobie** [comment]
Fixed in #185

**Pull request merged**
