### PR TITLE
Document where W3C/IETF import scripts are

### PR DESCRIPTION
**Pull request by strugee**
I couldn't find this myself, so I figured I would document it for others. `rdf.js` in particular isn't very well-named.

### CODE REVIEW

**Comment by tobie** [comment]
Yeah. There's a lot of legacy stuff lying around.

We could also just rename the files, no?

**Comment by strugee** [comment]
@tobie I'd be happy to do that, just wasn't sure what other stuff would break because it expected those filenames

**Comment by tobie** [comment]
@strugee awesome.

I think if you just rename `rdf.js` -> `w3c.js` and `rfc.js` -> to `ietf.js` and fix both those references in `udate-all`, you should be good. :crossed_fingers:

**Comment by tobie** [comment]
There's a bunch more scripts in `scripts/fetch-helpers`, btw.

Also curious as to what brought you to check out Specref's innards, if you're able to share.

**Comment by strugee** [comment]
> Also curious as to what brought you to check out Specref's innards, if you're able to share.

I wanted to write a script to automatically pull in specs from http://microformats.org, but it turned out to be too complicated to parse automatically and they don't change that often anyway. So #370 happened instead :)

**Comment by strugee** [comment]
Closing and will submit a new PR with the rename.

**Pull request closed without merging**
