### PR TITLE
fixup location of WebCrypto editors' draft

### PR DESCRIPTION
**Pull request by equalsJeffH**
hope this helps, =JeffH

### CODE REVIEW

**Comment by tobie** [comment]
This is a it convoluted, and I apologize, but you need to fix this here instead: https://github.com/tobie/specref/blob/master/overwrites/w3c.json

**Comment by equalsJeffH** [comment]
done.  btw, what's "WG21"  and why does it matter?  and what's the purpose of "overwrites"?  perhaps this should be documented ?   :)

**Comment by tobie** [comment]
> btw, what's "WG21" and why does it matter?

An ISO group that standardises C++.

> and what's the purpose of "overwrites"?

It's the easiest way I coud find to fix references while still allowing to update references automatically. 

> perhaps this should be documented ? :)

PR welcome. :)

Alternatively, if someone is willing to pay me to work on Specref, I'd be happy to oblige.

**Comment by tobie** [comment]
This changes the ED of WebIDL, btw. Not WebCrypto.

**Comment by equalsJeffH** [comment]
doh. thanks for catching that.

**Comment by tobie** [comment]
:)

**Pull request merged**
